### ISSUE TITLE
portable-atomic-util: Rewrite Arc based on std::sync::Arc

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/portable-atomic#140]
When I reviewed https://github.com/taiki-e/portable-atomic/pull/41, I thought the differences in its implementation were fine, but in reality, we have missed several problems that would not have occurred if the implementation had been based on std::sync::Arc (#137, #139).

This will not necessarily be easy, since the standard library uses many unstable features.

**Comment by notgull** [comment]
When I was originally writing the `Arc` code, I tried to follow along with the standard library's version, but polyfilling bits and pieces in when unstable features were used.

It might be nice to bump the MSRV of `portable-atomic-util` higher than 1.34 so we gain access to some of these features, such as `addr_of`.

**Comment by taiki-e** [comment]
The draft implementation is in #142. addr_of_mut in as_ptr is not really important; the layout calculation is needed anyway to implement from_raw, and it can be used in as_ptr, so making the layout calculation work in the older version is the important point.

**Comment by taiki-e** [comment]
As a side effect of this work, I found UBs in std Arc/Rc.
https://github.com/rust-lang/rust/issues/119241
