### ISSUE TITLE
portable-atomic-util: Example for Arc<dyn Trait>

### ISSUE THREAD

**Issue by piotrfila** [taiki-e/portable-atomic#143]
Hello,
I am trying to port a crate that uses `Arc<dyn Trait>` for dynamic dispatch to but I could not find a way to do this with this crate.
Minimal example:
``` rust
trait MyTrait {
    fn do_stuff(&self, x: &mut u32);
}

struct Foo(u32);

impl MyTrait for Foo {
    fn do_stuff(&self, x: &mut u32) {
        *x = self.0;
    }
}

fn main()  {
    use portable_atomic_util::Arc;
    let arc = Arc::new(Foo(42)) as Arc<dyn MyTrait>;

    let mut x = 0;
    arc.do_stuff(&mut x);
}
```
The error I get: `an 'as' expression can only be used to convert between primitive types or to coerce to a specific trait object`.
This example works if `use portable_atomic_util::Arc;` is replaced with `use alloc::sync::Arc;`, though the latter is not available on my target architecture (thumbv6m),.
I also tried calling `.into()` and `.try_into()` on the Arc, as well as converting the Foo object like this:
``` rust
    let arc = Arc::new(*(&Foo(42) as &dyn MyTrait));
```
but those methods work neither on this crate's Arc nor alloc's.

Is there a way to do this using this crate?

**Comment by taiki-e** [comment]
Unfortunately, AFAIK, to make this work requires unstable [CoerceUnsized](https://doc.rust-lang.org/nightly/core/ops/trait.CoerceUnsized.html) trait (https://github.com/rust-lang/rust/issues/18598).
See also [the Rust reference](https://doc.rust-lang.org/nightly/reference/type-coercions.html#unsized-coercions).

> Note: While the definition of the unsized coercions and their implementation has been stabilized, the traits themselves are not yet stable and therefore can't be used directly in stable Rust.

**Comment by taiki-e** [comment]
Once #142 is merged, conversion from Box is supported, so we can emulate CoerceUnsized with stable rustc via Box:

```rs
let boxed: Box<dyn ...> = Box::new(Foo(42));
let arc: Arc<dyn ...> = Arc::from(boxed);
```

However, the current rustc can omit the allocation of Box if T is Sized (https://godbolt.org/z/s49WxEcan), but unfortunately it cannot omit it if T is Unsized (https://godbolt.org/z/f55oWG1rW), so the generated code will not be the best.

**Comment by taiki-e** [comment]
This limitation is now documented with the link to the [known workaround](https://github.com/taiki-e/portable-atomic/issues/143#issuecomment-1866488569) (https://github.com/taiki-e/portable-atomic/commit/a8cc61b2ac9ec7ce6aa1be6a496998060b8e87fd).
