### ISSUE TITLE
Add a replacement for `std::sync::Arc` that uses `portable-atomic::AtomicUsize`

### ISSUE THREAD

**Issue by notgull** [taiki-e/portable-atomic#37]
There should be an `alloc` feature that provides a replacement for `Arc` that uses `portable_atomic::AtomicUsize` instead of the standard library version. This would allow users of `portable_atomic` to use `Arc` on targets where atomics are not supported but allocation is.

However, this may be better suited for an alternate crate instead of this crate. I can implement either if desired.

**Comment by taiki-e** [comment]
Sounds good.
I was thinking it would be nice to have a crate (something like `portable-atomic-util` or `portable-atomic-extra`) to put in utilities like #8 that are more difficult to decide about API than existing APIs, but putting `Arc` in it seems like a good idea.
